### ISSUE TITLE
CR pages in other language than English US are not parseable

### ISSUE THREAD

**Issue by Godzil** [Godzil/Crunchy#1]
If crunchy try to get an anime page from a non english version of CR, it does not parse correctly the page.

Solution would be to use the RSS file instead of the web page:

Use

http://www.**.com/gintama.rss

instead of

http://www.**.com/gintama

This must be done transparently to the end user.

**Comment by Jfigs101** [comment]
Can this be made as an option? I worry that, for example, the RSS for One Piece is broken. It is showing the new Gold movie as the latest episode.

**Comment by Godzil** [comment]
Hum? weird, are you sure it's in the episode list?
The iOS/Android/WiiU/... version of CR does not use the same mecanisme to get episodes list as the website, they use something like the RSS feed which seemed pretty stable on what I've looked.

Anyway there is currently no easy way to support of possible languges in CR, I will take a look at the one you talk about.

**Comment by Jfigs101** [comment]
This is what I was talking about: http://feeds.feedburner.com/crunchyroll/one-piece

Note how there is only one episode. The latest movie. Compare to: http://feeds.feedburner.com/crunchyroll/naruto

**Comment by Godzil** [comment]
Yes I see the same thing, but are you sure that.. There this is not true and CR only have that movie?

**Comment by Jfigs101** [comment]
I am sure. CR has all the episodes licensed in the US.

**Comment by Godzil** [comment]
Ok, I will probably add some debug options to allow me to understand page layout when I can get the page on my side.

**Comment by Jfigs101** [comment]
Yes, correct. I agree. There are a couple complaints in the crunchyroll forums regarding this issue.
