### ISSUE TITLE
-t flag

### ISSUE THREAD

**Issue by xXxBobDolexXx** [Godzil/Crunchy#10]
When using the -t flag, is there any way to have the tag set to nothing, instead of having to put a character?

 By default it adds the word crunchyroll to every filename, would like it to just be "<title> - <S01E01>.mkv"

**Comment by Godzil** [comment]
Have you tried -t "" ? But to be honest the code is not made to remove the tag.

You can use a batch renamer if you really want to remove that part of the filename, it will be easier

**Comment by xXxBobDolexXx** [comment]
Using -t "" doesn't do anything, keeps the [CrunchyRoll] but I'll just use
the bulk rename utility as suggested. Thanks!

**Comment by Godzil** [comment]
This is not normal that -t "" do nothing
