### ISSUE TITLE
Subtitles not merging with the video

### ISSUE THREAD

**Issue by Oujiii** [Godzil/Crunchy#101]
**Describe the bug**
The video is not merging with the subtitles, I'm getting a MP4 video and an ASS subtitle.

**Expected behavior**
I expected for it  

**Screenshots**

**Please fill theses informations:**
(Add a X between brackets to make them ticked if relevant)
 - OS: Linux Mint 19 Cinnamon
 - [X] I'm using the latest version of Crunchy
 - [X] I have a premium accrount on CR
 - [ ] I am using a VPN
 - My region in the world (country or continent): Brazil
 - Serie you get a problem with (and specify which episode if it is specific to one): Say "I love you"
 - The command line you are running Crunchy with: crunchy --verbose -b cr
 - The message Crunchy is giving you, if any: Normal message finished message

**Additional context**
I verbosed everything from the command and it is here: https://pastebin.com/VbfqknBW

For further context, I downloaded these same episodes on another computer with Mint 19 and it worked without issue. I tried reinstalling mkvtoolnix and crunchy itself but the issue persists.

**Comment by Godzil** [comment]
what does your `cr` file contain on the line for that specific anime?

Could you have a stray `-m` on the line?

**Comment by Oujiii** [comment]
The `cr` file contains only the line `https://www.crunchyroll.com/say-i-love-you -e 1`

I guess that when reinstalling, I forgot to delete the config.json, as I always use the same folder to download the episodes.
Doing that solved the issue.

Also, it's worth noting that for a while, I am unable to download individual episodes linking them directly. #102

I'm gonna close this issue. Thank you very much!
