### ISSUE TITLE
Can't download single episodes using the direct link

### ISSUE THREAD

**Issue by Oujiii** [Godzil/Crunchy#102]
**Describe the bug**
If I try to download a single episode from an anime using the direct link to the episode, it will try to search a different anime and won't download

**Expected behavior**
The specific episode should download

**Screenshots**
![Terminal](https://i.imgur.com/sCFx797.png)

**Please fill theses informations:**
(Add a X between brackets to make them ticked if relevant)
 - OS: Mint 19 Cinnamon
 - [X] I'm using the latest version of Crunchy
 - [X] I have a premium accrount on CR
 - My region in the world (country or continent): Brazil
 - Serie you get a problem with (and specify which episode if it is specific to one): Every anime
 - The command line you are running Crunchy with:` crunchy https://www.crunchyroll.com/say-i-love-you/episode-7-i-really-love-you-613761` (this can be really with any link)
 - The message Crunchy is giving you, if any:
```
ouji@1700:~/Animes$ crunchy https://www.crunchyroll.com/say-i-love-you/episode-7-i-really-love-you-613761
 * INFO : Crunchy version 1.4.5
 * INFO : You have a premium account! Good!
 * INFO : Checking availability for Hayate no Gotoku!Shugo Chara
 * WARN : No episodes found for Hayate no Gotoku!Shugo Chara. Could it be a movie?
Done!
```

**Additional context**
It used to work before.

**Comment by Godzil** [comment]
To use a direct link you need to prefix the URL with an @
