### ISSUE TITLE
Unable to download without using direct link

### ISSUE THREAD

**Issue by Oujiii** [Godzil/Crunchy#107]
**Describe the bug**
I'm unable to download whole series ou parts of it using the link of the series, even in batch files

**Expected behavior**
I expect it to download the whole series or the episodes specified in the -e parameter

**Please fill theses informations:**
(Add a X between brackets to make them ticked if relevant)
 - OS: Linux Mint 19.1 and Ubuntu Server 18.04.1
 - [X] I'm using the latest version of Crunchy
 - [X] I have a premium accrount on CR
 - [ ] I am using a VPN
 - My region in the world (country or continent): BR in Linux Mint and US in the Ubuntu Server
 - Serie you get a problem with (and specify which episode if it is specific to one): Any episode of any series
 - The command line you are running Crunchy with: `crunchy -b cr`
 - The message Crunchy is giving you, if any:
````bash
$ crunchy -b cr
 * INFO : Crunchy version 1.4.6
 * INFO : Seems we are not currently logged. Let's login!
 * ERROR: Cannot get episodes from "https://www.crunchyroll.com/attack-on-titan", please rerun later
Done!
````

**Additional context**
In this example, the batch file reads:
````
https://www.crunchyroll.com/attack-on-titan -e 10-20
````
Even if I try only `crunchy https://www.crunchyroll.com/attack-on-titan` the issue is the same

**Comment by UberMentch** [comment]
I've been having a similar issue since at least yesterday, it was working for me last Friday. I can't seem to get any episodes, even single ones. Goes for any show, including episodes I've previously downloaded, and episodes that I've never downloaded.

> crunchy -u myusername -p mypass -e 146 -o G:\Shows\ https://www.crunchyroll.com/jojos-bizarre-adventure/

**Comment by Oujiii** [comment]
For single episodes, using the @directlink works for me, but that's about it.

**Comment by UberMentch** [comment]
Didn't realize that was a thing I could do, cheers! Worked perfectly. Still would like to see this issue resolved

**Comment by Godzil** [comment]
They must have change the layout of the episodes pages. But I can’t check that at the moment
