### ISSUE TITLE
Getting 'Ignoring: not release yet' error for new episodes

### ISSUE THREAD

**Issue by lonewolf8209** [Godzil/Crunchy#110]
**Describe the bug**
Tried to download newly released episodes and getting "Ignoring: not released yet" error.

**Expected behavior**
Download new episode.

**Screenshots**
![image](https://user-images.githubusercontent.com/51878596/62418268-fc42c400-b600-11e9-9349-4734cceaaf2b.png)

**Please fill theses informations:**
(Add a X between brackets to make them ticked if relevant)
 - OS: [e.g:. Windows 10, Mac OS X 10.13, ...] Windows 10 with WSL
 - [X] I'm using the latest version of Crunchy
 - [X] I have a premium accrount on CR
 - [ ] I am using a VPN
 - My region in the world (country or continent):US
 - Serie you get a problem with (and specify which episode if it is specific to one):Just new episodes
 - The command line you are running Crunchy with:"crunchy @link" and "crunchy -b cr.txt"
 - The message Crunchy is giving you, if any:Ignoring: not released yet

**Please be careful to remove your real account login and password if they appear!**

**Additional context**
Only getting error on newly released episodes, all other episodes work fine.

_Also don't hesitate to add labels you feel apropriate on your report._
_Please don't edit logs if you are adding them, apart from removing sensitive informations like login/password_

**Comment by mikkerlo** [comment]
+1
Have a same error with the 6 six episode of the same anime

**Comment by Godzil** [comment]
Can you actually watch them on the website?

**Comment by lonewolf8209** [comment]
> Can you actually watch them on the website?

Yeah, they are new releases. I can watch them on the site, but, when i try to download them, i get that error.

**Comment by mikkerlo** [comment]
> Can you actually watch them on the website?

Yeah, but only with premium account

**Comment by Godzil** [comment]
Hmmmm seems the “log fix” don’t fix everything in fact. 

Damn

**Comment by lonewolf8209** [comment]
I've been using youtube-dl for the newer episodes

**Comment by Jfigs101** [comment]
This is happening to me too

**Comment by ae-bogdan** [comment]
Still happening here

**Comment by Godzil** [comment]
Linked with the “fix” for #103, fixing it will fix this one.
