### ISSUE TITLE
Unable to download at 1080p

### ISSUE THREAD

**Issue by Jfigs101** [Godzil/Crunchy#111]
**Describe the bug**
Crunchy downloading at 480p, unable to download at 1080p

**Expected behavior**
By default, Crunchy should download at 1080p

**Please fill theses informations:**
(Add a X between brackets to make them ticked if relevant)
 - OS: [Ubuntu 18.04]
 - [X] I'm using the latest version of Crunchy
 - [X] I have a premium accrount on CR
 - [ ] I am using a VPN
 - My region in the world (country or continent): USA
 - Serie you get a problem with (and specify which episode if it is specific to one): All
 - The command line you are running Crunchy with: crunchy -u X -p X -o /mnt/X/Anime/ @https://www.crunchyroll.com/demon-slayer-kimetsu-no-yaiba/episode-2-trainer-sakonji-urokodaki-782933

 - The message Crunchy is giving you, if any: N/A

**Comment by Godzil** [comment]
Ok so that’s clear, the “fix” seems to create more problems than it solved...

**Comment by Godzil** [comment]
See bug #103 which is the original problem
