### ISSUE TITLE
only get 480p

### ISSUE THREAD

**Issue by storm134** [Godzil/Crunchy#114]
**Describe the bug**
only download 480p now after updating nodejs (fixed error 113)

**Expected behavior**
should get 720 or 1080 depending on what i set

**Screenshots**

**Please fill theses informations:**
(Add a X between brackets to make them ticked if relevant)
 - OS: [e.g:. Windows 10, Mac OS X 10.13, ...] window 10
 - [ x] I'm using the latest version of Crunchy
 - [x ] I have a premium accrount on CR
 - [ ] I am using a VPN
 - My region in the world (country or continent):canada
 - Serie you get a problem with (and specify which episode if it is specific to one):
if-its-for-my-daughter-id-even-defeat-a-demon-lord
 - The command line you are running Crunchy with:
crunchy -u [username] -p [password] -r 720 --output c:\drivers\crunchy @https://www.crunchyroll.com/if-its-for-my-daughter-id-even-defeat-a-demon-lord/episode-3-the-young-man-heads-out-786960
 - The message Crunchy is giving you, if any:
no error

**Please be careful to remove your real account login and password if they appear!**

**Additional context**
crunchy -u [username] -p [password] -r 720 --output c:\drivers\crunchy @https://www.crunchyroll.com/if-its-for-my-daughter-id-even-defeat-a-demon-lord/episode-3-the-young-man-heads-out-786960
 * INFO : Crunchy version 1.5.0
 * INFO : Trying to fetch from https://www.crunchyroll.com/if-its-for-my-daughter-id-even-defeat-a-demon-lord/episode-3-the-young-man-heads-out-786960
 * WARN : Authentication failed:
 * INFO : Seems we are not currently logged. Let's login!
 * INFO : You have a premium account! Good!
 > If It_s for My Daughter, I_d Even Defeat a Demon Lord - s01e03 - The Young Man Heads Out - [CrunchyRoll] : Fetching.. > If It_s for My Daughter, I_d Even Defeat a Demon Lord - s01e03 - The Young Man Heads Out - [CrunchyRoll] : Fetching v > If It_s for My Daughter, I_d Even Defeat a Demon Lord - s01e03 - The Young Man Heads Out - [CrunchyRoll] : Finished! (00:01:21)
Done!

_Also don't hesitate to add labels you feel apropriate on your report._
_Please don't edit logs if you are adding them, apart from removing sensitive informations like login/password_

**Comment by Godzil** [comment]
Thanks for the report but #111 report the same issue
