### ISSUE TITLE
crLocale not working

### ISSUE THREAD

**Issue by caiquejd** [Godzil/Crunchy#115]
I'm trying to use crLocale in config.json to choose Portugue-Brazilian language, but do not seems to work, and Crunchy only ignores showing:
 * INFO : No locale set. Setting to the one reported by CR: "en"

I'm using this format:

{
  "format": "ass",
  "tag": "CrunchyRoll",
  "resolution": "720",
  "retry": 5,
  "nametmpl": "{SERIES_TITLE} - s{SEASON_NUMBER}e{EPISODE_NUMBER} - {EPISODE_TITLE} - [{TAG}]",
  "user": "***********",
  "pass": "***********",
  "crLocale": "pt-br",
  "output": "D:\\Animes\\OP"
}

How I can change de subtitle language?

**Comment by jpalomino1991** [comment]
I have take a look in the code and it only retrieve the first sub it comes in the video. So it won't look for the right sub you are looking for.

I'm making changes in the code so it can look and try to retrieve the set subtitle in the config file.

Also according to the code the right format is ptBR.

**Comment by Godzil** [comment]
crLocal is not to download a specific language for subtitles but to be able to parse properly Cr pages that are translated. Choosing langages for subtitles will come in a future version.

**Comment by Godzil** [comment]
1.6 release add the ability to choose subtitles languages.
