### ISSUE TITLE
problem language

### ISSUE THREAD

**Issue by nunurs89** [Godzil/Crunchy#119]
**Describe the bug**
When I start the download it indicates an error

**Expected behavior**
C:\Users\Nunurs>crunchy -u xxxxxxxxxx -p xxxxxxxxx -l frFR http://www.crunchyroll.com/fr/the-8th-son-are-you-kidding-me/episode-2-a-succession-dispute-are-you-kidding-me-794535
 * INFO : Crunchy version 1.5.0
 * WARN : Crunchy is configured for locale "frFR" but CR report "en" (LOCALE = enUS)
 * WARN : Check if it is correct or rerun (once) with "-l en" to correct.
 * WARN : Authentication failed:
 * INFO : Seems we are not currently logged. Let's login!
 * WARN : Crunchy is configured for locale "frFR" but CR report "en" (LOCALE = enUS)
 * WARN : Check if it is correct or rerun (once) with "-l en" to correct.
 * INFO : You have a premium account! Good!
 * INFO : Checking availability for Crunchyroll
 * WARN : No episodes found for Crunchyroll. Could it be a movie?

**Screenshots**

**Please fill theses informations:**
(Add a X between brackets to make them ticked if relevant)
 - OS: [e.g:. Windows 10, Mac OS X 10.13, ...]
 - [x] I'm using the latest version of Crunchy
 - [x] I have a premium accrount on CR
 - [ ] I am using a VPN
 - My region in the world (country or continent): french
 - Serie you get a problem with (and specify which episode if it is specific to one):
all series
 - The command line you are running Crunchy with:

crunchy -u xxxxxxxxxx -p xxxxxxxxx -l frFR http://www.crunchyroll.com/fr/the-8th-son-are-you-kidding-me/episode-2-a-succession-dispute-are-you-kidding-me-794535

 - The message Crunchy is giving you, if any:
 * INFO : Crunchy version 1.5.0
 * WARN : Crunchy is configured for locale "frFR" but CR report "en" (LOCALE = enUS)
 * WARN : Check if it is correct or rerun (once) with "-l en" to correct.
 * WARN : Authentication failed:
 * INFO : Seems we are not currently logged. Let's login!
 * WARN : Crunchy is configured for locale "frFR" but CR report "en" (LOCALE = enUS)
 * WARN : Check if it is correct or rerun (once) with "-l en" to correct.
 * INFO : You have a premium account! Good!
 * INFO : Checking availability for Crunchyroll
 * WARN : No episodes found for Crunchyroll. Could it be a movie?

**Comment by Godzil** [comment]
Couple of problems:

* You don't need to force the language local. Crunchy get it by default, it is more for testing purpose this option exist
* `frFR` is not a valid value, `fr` is. The local is only used to parse the pages it have no other impact.
* Do not add the `/fr` in the URL. It may work with, but that's not the real address to a page
* If you link to an actual episode you have to use the `@url` format else it will fail as you see en the end.

So the URL should be something like `@http://www.cr.com/series/episodename-number`

**Comment by nunurs89** [comment]
i have a problem...

C:\Users\Nunurs>crunchy -u xxxxxxxx -p xxxxxx @https://www.crunchyroll.com/my-next-life-as-a-villainess-all-routes-lead-to-doom/episode-2-a-prince-challenged-me-to-a-fight-794620
 * INFO : Crunchy version 1.5.0
 * INFO : Trying to fetch from https://www.crunchyroll.com/my-next-life-as-a-villainess-all-routes-lead-to-doom/episode-2-a-prince-challenged-me-to-a-fight-794620
 * INFO : No locale set. Setting to the one reported by CR: "en"
 * WARN : Authentication failed:
 * INFO : Seems we are not currently logged. Let's login!
 * INFO : You have a premium account! Good!
 > My Next Life as a Villainess_ All Routes Lead to Doom! - s01e02 - A Prince Challenged Me to a Fight___ - [CrunchyRoll] : Ignoring: not released yet
Done!

it's say i'm connect with premium account and say "not released yet" but it's yet release and if i download first épisode (no premium required, it downloaded in 480p) and only in EN language, when i put "l -fr"

 * WARN : Crunchy is configured for locale "fr" but CR report "en" (LOCALE = enUS)
 * WARN : Check if it is correct or rerun (once) with "-l en" to correct.
 

so only download in free mode and only in english, have you an idea?

**Comment by Godzil** [comment]
This is another problem that was introduced by a change supposed to fix a login issue. I didn’t had the time to look at that yet (Bug #103)

**Comment by Godzil** [comment]
Could you try with the latest version to see if it fix the issue?

Merci

**Comment by nunurs89** [comment]
Yes thx the problem "premium account" it's solved :)
but not in french language

C:\Users\Nunurs>crunchy @http://www.crunchyroll.com/fr/princess-connect-re-dive/episode-2-a-moody-cats-mischief-warm-golden-rice-balls-794688
 * INFO : Crunchy version 1.5.1
 * INFO : Trying to fetch from http://www.crunchyroll.com/fr/princess-connect-re-dive/episode-2-a-moody-cats-mischief-warm-golden-rice-balls-794688
 * WARN : Crunchy is configured for locale "fr" but CR report "en" (LOCALE = enUS)
 * WARN : Check if it is correct or rerun (once) with "-l en" to correct.
 * WARN : Authentication failed:
 * INFO : Seems we are not currently logged. Let's login!
 * WARN : Crunchy is configured for locale "fr" but CR report "en" (LOCALE = enUS)
 * WARN : Check if it is correct or rerun (once) with "-l en" to correct.
 * INFO : You have a premium account! Good!
 > Princess Connect! Re_ Dive - s01e02 - Menu 2 – La farce du chat capricieux - [CrunchyRoll] : Finished! (00:03:13)
Done!


file config.json
{
  "format": "ass",
  "tag": "CrunchyRoll",
  "resolution": "1080",
  "retry": "5",
  "crlang": "fr",
  "user": "xxxx",
  "pass": "xxxxxxx",
  "nametmpl": "{SERIES_TITLE} - s{SEASON_NUMBER}e{EPISODE_NUMBER} - {EPISODE_TITLE} - [{TAG}]"
}

i want to download subtitles in french language, where i did wrong please?

**Comment by nunurs89** [comment]
i have test with url  http://www.crunchyroll.com/fr/.... and  http://www.crunchyroll.com/......

**Comment by Godzil** [comment]
The “local” is for the tool to be able to read the info from CR pages, not download french dubs or subtitles. It does not really matter what is is set really.

**Comment by nunurs89** [comment]
So it's only working in English for the moment.
Thank for helping @Godzil 
I will waiting for other language for use this tool thank :)
