### ISSUE TITLE
All attempts to download failing

### ISSUE THREAD

**Issue by froggiepunch** [Godzil/Crunchy#121]
I keep getting "ERROR: {"errno":-3,"code":"Z_DATA_ERROR"}" when trying to download a series, each episode tries to download 5 times then it moves on to the next one, each with the same error. I'm not sure what's wrong, as I've used this before to download things without issue

**Comment by Godzil** [comment]
If it work on some series/episodes and not on other, it is because things have changed on CR at some point in the last year.

A new release of crunchy should be released in a couple of days (hours?) please test again once it is released, it will probably solve that issue.

**Comment by froggiepunch** [comment]
Oh, I meant that older versions have worked in the past but the current version does not work on either my macbook or windows pc. Both throw out the same error. I will test out the update when it's out

**Comment by froggiepunch** [comment]
Okay so I've updated and I tested a series, and it seems to be working now, no more errors! If it stops working again, I'll report back but I'll close this for now, thank you so much!
