### ISSUE TITLE
File Resolution Size

### ISSUE THREAD

**Issue by JySzE** [Godzil/Crunchy#20]
When downloading on linux and windows even after entering in my crunchyroll login and setting my video preference settings on my account to 1080p, I keep ending up with a res size of "848x480" I tried this with DBS, naruto shippuden (episodes that are 1080p) and also fairy tail. All ending up with the same resolution... Very confused here tried to do as much as i could before opening an issue. Thanks.
![screenshot_1](https://cloud.githubusercontent.com/assets/25883052/23103936/a7706e4a-f678-11e6-91b2-a643bc564ffc.png)

Jacob--

**Comment by Godzil** [comment]
Crunchy have no control on that, I will check on my side when possible, but I suspect it is a "bug" on CR side more on Crunchy side.

Try to check on the US version of CR website if the setting is correct.

**Comment by JySzE** [comment]
Yeah im on the US version of CR and have confirmed my settings i have enabled everything but full screen hardware acceleration if that makes any difference?: 

![screenshot_2](https://cloud.githubusercontent.com/assets/25883052/23105584/66b0e420-f696-11e6-86b0-eeeab240c966.png)

**Comment by JySzE** [comment]
Just fixed the issue it was user error sorry for issue post. 

I was unaware that you had to set the -u and -p command in conjunction every time you started a download. I thought you had to enter the commands independently and the login info was then logged and fetched each time you started a new download. 

Inccorectly using `crunchy --output C:\Anime http://www.crunchyroll.com/dragon-ball-super`
Corrected: `crunchy C:\Anime http://www.crunchyroll.com/dragon-ball-super -u [username] -p [password]`

**Comment by Godzil** [comment]
Good to know, thanks!

It's something planned, to keep credential between calls, but I need to do a lot of changes in Cunchy to support that, so yes, for now keep the username/password on the command line, sorry for that :disappointed:

**Comment by JySzE** [comment]
No need for apologies 😄, with or without the feature of saving and fetching credentials I have nothing but great pleasure using Crunchy.

Thanks for all your hard work I can't thank you enough! 

Some newbies out there like myself 😅 may run into this issue, so if you could update the examples to include the usage of Authentication properly that would help out others greatly. 👍 

Thanks, 

Jacob--

**Comment by Godzil** [comment]
Just as a note: well long later after that, I added proper parameter to set the resolution since version 1.2.0
