### ISSUE TITLE
Preserve Watermarks on downloaded Videos

### ISSUE THREAD

**Issue by factorcore** [Godzil/Crunchy#21]
Add the option to preserve the Watermarks Exclusive Stream for, and the random CR logo in top right-hand corner.

**Comment by Godzil** [comment]
There is no such option because it is not part of the stream. I would need to re-encode the video to add such a watermark.

**Comment by factorcore** [comment]
Thank you for the quick response. I thought it was part of the stream.

**Comment by Godzil** [comment]
To make things clear, and I understand your question, I don't want Crunchy to be used for illegal purpose like piracy. Its use is already in the gray area for people that have a proper account, I'm not enforcing yet the use of Premium account, but it may happen soon, as I said, CR would add an official way (even with the need to pay a higher monthly amount) I would be even more than happy to update Crunchy to support there new thing and make sure it can't be used without. Unfortunately it looks like they don't want to go on that way, and really, I have more time offline to watch anime than online, hence why I resurrect that project and maintain it.

So CR, if you read this message, and I'm sure you will read it at some point, as a premium user I would be way more than happy to pay more to have an official offline access, as probably most of the user of this tool.

**Comment by factorcore** [comment]
The organization I work with has written permission to download for our events. This seemed like the best way to obtain the downloads without having to watch every stream with a screen capture, I'll need to re-read the agreement to see if there is another way to comply with our agreement. 

Thanks
