### ISSUE TITLE
Download a specific episode via specific url?

### ISSUE THREAD

**Issue by eisnerguy1** [Godzil/Crunchy#23]
I'm trying to figure out how to download a specific episode.  I've tried the -e & -v flags but neither work.  Like for instance, the "Digimon Adventure tri – PV" video:
http://www.crunchyroll.com/digimon-adventure-tri/digimon-adventure-tri-pv-688947

How can I download just that via Crunchy?

**Comment by Godzil** [comment]
It is not specified in the documentation (yet) but there is the "@" syntax as descrived in issue #11 

crunchy @http://

instead of

crunchy http://

Does that solve your problem?

**Comment by eisnerguy1** [comment]
Yep! That worked!  Thanks!
