### ISSUE TITLE
Something Unexpected in the page

### ISSUE THREAD

**Issue by JySzE** [Godzil/Crunchy#24]
![untitled](https://cloud.githubusercontent.com/assets/25883052/25069076/dfaf2ede-222b-11e7-98af-207183754385.png)
Im trying to download episode 120-210

And 5 times during the download it says "something unexpected in the page (data are: )"

Also "Somethig" in "Something unexpected" is a spelling error (not related just wanted to mention it)

**Comment by Godzil** [comment]
Yup there is a spelling error, hum I haven't met yet that issue, but I hope they haven't changed the page layout again..
