### ISSUE TITLE
Long titles, maybe special characters cause issue.

### ISSUE THREAD

**Issue by Ganabei** [Godzil/Crunchy#26]
It seems either long titles or maybe colons/special characters prevent fetching of data.  Noticed it when I was trying to grab 'WorldEnd: What do you do at the end of the world? Are you Busy?  Will you Save us?' but it just hangs on 'Checking availability' after the Premium message, no error code or anything.  I was able to get around it by putting a -s 1 into the command line which ended up giving it a blank title.  Episodes are listed as '- s1e1' and '- s1e2'  Folder was just called '1'.  Saw someone else had an issue with Re:Zero, which is what made me think it might be the colon and how names are fetched and put into files.

**Comment by Godzil** [comment]
That's interesting, I will check, I know of only one character that fail (but not directly on crunchy side unfortunately) the @ symbol is redacted as if it was to remove an email from the page by something before I retrieve the page and it screw the thing. It happen on "THE IDOLM@STER CINDERELLA GIRLS" for example..

**Comment by jp1995** [comment]
Can confirm this is an issue, just happened to me trying to download Problem Children are Coming from Another World, aren't they?. OP's workaround works for me too.

**Comment by Godzil** [comment]
There is no issues as far as I know with Re:Zero. There were an issue long time ago, but characters like ":" are correctly managed now. Maybe the "?" is the culprit there. I will check.

**Comment by Ganabei** [comment]
I'm on windows, and they don't allow ? in file names.  Imagine that's what the other poster is having issues with as well.

**Comment by Godzil** [comment]
Hummm yes I think you are right "?" are allowed under Linux/Mac OS Xm but probably not under windows. I will put that in the list of characters that have to be replace

**Comment by Ganabei** [comment]
Windows loves their restrictions.  These are the characters Windows doesn't allow \ / : * ? " < > |

**Comment by Godzil** [comment]
Will close that issue as I think there is no problem anymore.
Please don't hesitate to reopen if some other character cause a problem
