### ISSUE TITLE
Unable to finish my download

### ISSUE THREAD

**Issue by sam5558** [Godzil/Crunchy#29]
Good plugin Godzil.
I started using this plugin, Worked great 'till 2 days ago when downloading an anime.

Here's the problem i'm facing; The plugin is executed normally, no apparent error displayed, but the download isn't progressing. 

It may be that crunchyroll servers are denynig access to the resources so that i'm unable to fetch my files.
P.S: I'm using a premium account.

Is there any suggestions ?

**Comment by Godzil** [comment]
I'm sorry without more information I don't know how I can help.

**Comment by sam5558** [comment]
Never Mind. I have found a workaroud to make it work.
If someone is facing the same phenomenon, please follow these steps : 

1/ Delete the current episode where download is stopped / very slow (~2kbps)
2/ Stop the crunchy command
3/ Re-run the command : "crunchy -u *** -p *** http://www.crunchyroll.com/***** --output /home/***/anime/" (for example)
4/ Now everything should be okay.

Enjoy 👍
