### ISSUE TITLE
Unable to download a specific anime

### ISSUE THREAD

**Issue by jp1995** [Godzil/Crunchy#30]
Hi. I'm trying to download High School DxD but I'm getting an error. I suspect that it is because it's not available in my country. Can you confirm?

`crunchy http://www.crunchyroll.com/high-school-dxd`

results in

```
Error: Invalid page.(http://www.crunchyroll.com/high-school-dxd)
    at /usr/lib/node_modules/crunchy/dist/series.js:127:29
    at /usr/lib/node_modules/crunchy/dist/request.js:23:13
    at giveResults (/usr/lib/node_modules/crunchy/node_modules/cloudscraper/index.js:244:5)
    at Request._callback (/usr/lib/node_modules/crunchy/node_modules/cloudscraper/index.js:109:7)
    at Request.self.callback (/usr/lib/node_modules/crunchy/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/lib/node_modules/crunchy/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
```

Assuming that the error is due to region blocking, how difficult would it be to implement functionality similar to the chrome extension, where the crunchyroll client is tricked into believing that the user is from the US?

Thanks!

**Comment by JySzE** [comment]
Use a vpn to change your location to somewhere in the US.

**Comment by jp1995** [comment]
Interesting, using a tunnelbear connection to the US and I'm still getting the same error.

**Comment by JySzE** [comment]
YMMV

Make sure when using tunnel bear you do not use any server located in california for some reason i have go try multiple different server locations within the US to be routed to the correct crunchyroll server that gives me no errors when downloading, AGAIN this is is all my own testing none of it is concrete and is gauranteed to work. 

I've noticed that crunchyroll chicago servers worked best for me.So connect to chicago via vpn and try the download again and also send me a copy of the entire command you are using to fetch the batch downloads any sensitive info replace with "*******"

**Comment by JySzE** [comment]
Also make sure when you are using a vpn you log into crunchyroll in your browser and set your country to USA. < Idk if thats possible to change region but worth a shot also. Also go to video preferences in settings and change it to 1080P so itll always grab the best quality when downloading.

**Comment by Godzil** [comment]
Are you sure you are logged, getting 480p looks like you are not, also the "something unexpected" is not normal.

**Comment by JySzE** [comment]
>  Remember that you need to give the login/password everytime you run crunchy!

Example: crunchy --output C:/Anime http://www.crunchyroll.com/Fairy-Tail **-u username -p password**

**Comment by jp1995** [comment]
This is really odd. Today I can download the previously discussed anime with no issues. Also, something else that's odd, I'm not getting the "Good, you have a premium account" message anymore, instead I get:

` * WARN : Do not use this app without a premium account.`

The username and password I passed in the same command are definitely correct. And I am getting 1080p video this time.

But I suppose my issue is resolved. You can close if you want, thanks for the help!

**Comment by Godzil** [comment]
That's really weird to get that message and still be able to receive a 1080p video.
The warning mean the app correctly logged and you don't have a premium account.
(trial account are not considered as premium by Crunchy and will trigger this WARN, *this is on purpose and will not be changed*)
So apart if you are using a trial account, I hope that CR haven't changed something there or it is going to be really annoying.

**Comment by jp1995** [comment]
Yep, I am using a trial account. It only seemed off to me because I got a different message before.
