### ISSUE TITLE
No episodes found for (Title). Could it be a movie?

### ISSUE THREAD

**Issue by 39-chan** [Godzil/Crunchy#32]
#I have a premium account, and yesterday, I can batch-download 3 title (One Room, YuruYuri and Eromanga-sensei)

but the next day, I'm trying to download another title (Hinako Note), it return me a error message saying that no episode found, even with the same title that I can download before

I used this command: crunchy -u user -p pass -o D:\path\to\folder http://www.crunchyroll.com/title

![console](https://cloud.githubusercontent.com/assets/28614753/25930824/adf6bf40-3632-11e7-873d-e5bf88cacf0a.jpg)

I used the same command as I'm downloading  One Room and YuruYuri.

**Comment by sam5558** [comment]
Are you using a VPN ? I remember having the same output message when using VPN. 
If so try to run your command without VPN.

**Comment by Godzil** [comment]
Can you access to these anime using the web interface?

I would try again just in case, CR is a bit.. hum ... fuzzy sometimes, and make sure if you normally are using a VPN that you really is connected.

Also a possibility is that CR is banning known VPN from accessing their website so please check that you can access the anime from the website.

The message that Crunchy reply mean that when it try to get the list of episode, the page was giving an empty list..

**Comment by AkaTako** [comment]
Yes, I can watch the anime using web interface

I also able download the anime with VPN connected / disconnected

**Comment by Godzil** [comment]
Is it still a problem?

**Comment by GNBRKR** [comment]
I got the same problem and I'm not using VPN, I can see the series in the web interface and I've tried with 10 different series.

**Comment by 39-chan** [comment]
I'm really sorry for not keep in-touch with you

I no longer have the tool in my system (because I refreshed my system) but I'm sure it's because I'm downloading it from blocked region

when I tried again to download some title with U.S VPN, I'm able to download it (before I refreshed my system)
