### ISSUE TITLE
Any way to change the naming scheme?

### ISSUE THREAD

**Issue by xXxBobDolexXx** [Godzil/Crunchy#34]
On crunchyroll itself, the filenames are like this:
Akashic Records of Bastard Magical Instructor Episode 4 – The Magic Competition

but with this tool it goes to:
Akashic Records of Bastard Magical Instructor - s01e04 - [CrunchyRoll]

I don't mind keeping the [CrunchyRoll] at the end, but is there a way to keep the formatting like it is already on crunchyroll?

**Comment by Godzil** [comment]
You should be able to use the change that came with the pull request #22 

Adding to your command line something like 

-n "{SERIES_TITLE} Episode {EPISODE_NUMBER} - {EPISODE_TITLE}"

should to the job

**Comment by xXxBobDolexXx** [comment]
Thank you!
