### ISSUE TITLE
Having problems figuring this out

### ISSUE THREAD

**Issue by tearsofdeath** [Godzil/Crunchy#35]
so im new to the whole node.js stuff so i'm having soe confusion. i'm trying to download fairy tail the this code. `crunchy --output F:\Media\Movies-shows\anime -p password -u user http://www.crunchyroll.com/fairy-tail`

i am trying to use the batch to do it but i'm a total noob so i cant really figure it out. could somone give me a step by step of what to from the start(do i need to install something or do i have to use a CD or something i keep getting `'crunchy' is not recognized as an internal or external command,
operable program or batch file.),` i would appreciate it alot.

-tears

**Comment by xXxBobDolexXx** [comment]
install the appropriate nodejs for your system
https://nodejs.org/en/download/

then enter this into the command prompt:
npm install -g crunchy

Then try your batch command again
