### ISSUE TITLE
ERROR: RTMP_HashSWF: swfurl

### ISSUE THREAD

**Issue by mellmo** [Godzil/Crunchy#37]
Greetings,

I've been getting the following error for a while now:

```
* INFO : You have a premium account! Good!
 * INFO : Checking availability for ------------
Error: Command failed: "C:\Users\----\AppData\Roaming\npm\node_modules\crunchy\bin\rtmpdump.exe" 
-r "rtmpe://cp150757.edgefcs.net/ondemand/?auth=------------------------/video.mp4" 
-y "mp4:-------/video.mp4" -W "http://www.crunchyroll.com/swf/StandardVideoPlayer-10dff2a.swf"
 -o "e:\anime\---------------------------------- [CrunchyRoll].mp4"

RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
ERROR: RTMP_HashSWF: swfurl http://www.crunchyroll.com/swf/StandardVideoPlayer-10dff2a.swf not found
Connecting ...
WARNING: HandShake: Type mismatch: client sent 6, server answered 8
INFO: Connected...
Starting download at: 0.000 kB
INFO: Metadata:
INFO:   duration              1417.44
INFO:   moovPosition          32.00
INFO:   width                 1920.00
INFO:   height                1080.00
INFO:   videocodecid          avc1
INFO:   audiocodecid          mp4a
INFO:   avcprofile            100.00
INFO:   avclevel              50.00
INFO:   aacaot                2.00
INFO:   videoframerate        23.98
INFO:   audiosamplerate       44100.00
INFO:   audiochannels         2.00
INFO: trackinfo:
INFO:   length                16991500.00
INFO:   timescale             11988.00
INFO:   language              und
INFO: sampledescription:
INFO:   sampletype            avc1
INFO:   length                62509056.00
INFO:   timescale             44100.00
INFO:   language              und
INFO: sampledescription:
INFO:   sampletype            mp4a
85.107 kB / 1.04 sec (0.0%)
WARNING: HandleInvoke, Sanity failed. no string method in invoke packet
WARNING: HandleInvoke, Sanity failed. no string method in invoke packet
WARNING: HandleInvoke, Sanity failed. no string method in invoke packet
262.003 kB / 1.25 sec (0.0%)
Download may be incomplete (downloaded about 0.00%), try resuming

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

```

when i check the player being loaded over crunchyroll website:
```http://www.crunchyroll.com/vendor/StandardVideoPlayer-10dff2a.swf```

I might be wrong but it seems like they moved their assests or something,

I've traced it to video/stream.js file but after a first glance & a global search i wasn't able to find the file that consume stream and provide the ```swfurl```

Any idea where to look ?

Thanks

**Comment by xXxBobDolexXx** [comment]
This one hasn't happened to me in a while, are you sure you have the most current version of crunchy?

**Comment by mellmo** [comment]
```
λ crunchy --version
1.1.19
```

Thanks

**Comment by xXxBobDolexXx** [comment]
Can I get the command and series you are trying to download? I'll check if it happens on my end

**Comment by mellmo** [comment]
```crunchy -p XXXX -u XXXX -o e:\anime http://www.crunchyroll.com/hunter-x-hunter```

Thanks

**Comment by xXxBobDolexXx** [comment]
Are you able to get any episodes before it happens or does it happen right away?

**Comment by mellmo** [comment]
sometimes right away, sometimes it download one episode and crashes

i've downloaded anime before without issue, maybe it's just this series

**Comment by xXxBobDolexXx** [comment]
Episode one is working fine for me so far. I'll let it run until episode 5 and let you know if it works for me. In the meantime, it might be worth removing nodejs and reinstalling it

**Comment by mellmo** [comment]
sure, i'll try that

Thanks for the quick reply, appreciated :)

**Comment by xXxBobDolexXx** [comment]
It took a while but episode 1 finished, episode 2 had some weird output so I stopped it, this is what happened when I reached episode 2

 > Hunter x Hunter - s01e01 - [CrunchyRoll] : Finished! (00:17:20)
 * WARN : Somethig unexpected in the page at http://www.crunchyroll.com/hunter-x-hunter/episode-2-test-x-of-x-tests-584888 (data are: )
 * WARN : Setting Season to ’0’ and episode to ’0’...

Which caused the episode to be titled " - s00e00 - [CrunchyRoll]"

**Comment by mellmo** [comment]
I am getting this after uninstalling and reinstalling crunchy xD

I'll just use the official website for a while 

Thanks xXxBobDolexXx 

```
C:\Users\------\AppData\Roaming\npm\node_modules\crunchy\dist\request.js:104
                    if ((dims[i] !== undefined) && (dims[i] !== '') && (dims[i] !== 'not-registered')) {
                             ^

TypeError: Cannot read property '1' of null
    at C:\Users\-------\AppData\Roaming\npm\node_modules\crunchy\dist\request.js:104:30
    at giveResults (C:\Users\-------\AppData\Roaming\npm\node_modules\crunchy\node_modules\cloudscraper\index.js:244:5)
    at Request._callback (C:\Users\--------\AppData\Roaming\npm\node_modules\crunchy\node_modules\cloudscraper\index.js:109:7)
    at Request.self.callback (C:\Users\--------\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\-------\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\------\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:1091:12)

```

**Comment by Godzil** [comment]
Without knowning the anime it is hard to help, but it happen a few times, and it seems it is some random measure that CR are using to prevent tools like Crunchy to work.

Wait a few hours or day and try again, it will work again.

I don't have yet a solution for that because it is too random and it is hard to investigate..

**Comment by Godzil** [comment]
@mellmo Do you still have that error? could you please fill another bug report with it as it is not related with the original.

Thanks

**Comment by mellmo** [comment]
Update: After many retries i successfully finished hunter-x-hunter, it seemed to happen only on some anime like HxH or fullmetal alchemist brotherhood

Is there an option to have something like forever with crunchy ? maybe a retry flag that specify the number and wait duration  that crunchy need to wait after a crash before retrying to fetch the asset again

Admittedly a hack but still better then nothing.

I'll close this for now, feel free to reopen it if needed,
Thanks

**Comment by Godzil** [comment]
As a note: Retrying has been added in version 1.3.1

**Comment by mellmo** [comment]
@Godzil much appreciated, thanks
