### ISSUE TITLE
only downloading subtitles

### ISSUE THREAD

**Issue by tearsofdeath** [Godzil/Crunchy#38]
everything is working fine but im only downloading subtitles. heres the code i used if your wondering `crunchy --output F:\Media\Movies-shows\anime -p password -u user http://www.crunchyroll.com/fairy-tail -e 6`

**Comment by xXxBobDolexXx** [comment]
I cannot recreate the issue using the same command. How long was the command running, and do you have the most updated version of crunchy?

**Comment by tearsofdeath** [comment]
yes i have the latest version, the command has been running for around 30 minutes. i have tried redoing it several times as well as deleting the anime folder

**Comment by xXxBobDolexXx** [comment]
It will probably have the same result, but this is the command I have hotkeyed to paste, as well as what your trying to do added to it. It's a little restructured, i have no idea if that matters or not but my success rate is very high with it. I've added what youre trying to do to this command so you should just need to fill yoru user and pass and then paste it into cmd

crunchy -u user -p pass -o F:\Media\Movies-shows\anime -f srt -m -e 6 http://www.crunchyroll.com/fairy-tail

**Comment by Godzil** [comment]
(bug apart, being able to just download subtitle would be an interesting feature) also being able to select one or multiple subtitles languages, but I don't really understand how CR are working on that point
