### ISSUE TITLE
Redundant import of `mkdirp`, and `fs`

### ISSUE THREAD

**Issue by ssttevee** [Godzil/Crunchy#45]
`mkdirp` is part of `fs-extra` so it doesn't need to be additionally installed. Also, `fs-extra` is be a drop-in replacement for the built in `fs` module so only one of them have to be imported. 

i.e.
https://github.com/Godzil/Crunchy/blob/10d71944d9c2a7729ca8efa80fee82a7c40a526f/src/episode.ts#L3-L4
and
https://github.com/Godzil/Crunchy/blob/10d71944d9c2a7729ca8efa80fee82a7c40a526f/src/series.ts#L4-L5

I'll do a PR for this after merging some other ones.

**Comment by Godzil** [comment]
the idea for fs-extra && fs: not change existing and working code.

Changing call from fs.* to fse.* was too risky to break something, same for mkdirp/fse/fs
