### ISSUE TITLE
Season filter?

### ISSUE THREAD

**Issue by tommypepsi** [Godzil/Crunchy#46]
I downloaded the first season of jojo' s bizarre adventure and it worked normally but after that it started redownloading the episode 3 with a  "-1" in the title where it downloaded multiple episode in one file ( when I try again it does the same thing ). I tried the episode filter with a 27 but it just downloaded every season from episode 27. Any way of doing a season filter instead?

**Comment by tommypepsi** [comment]
I noticed that there is a Re-Edited version of season one on crunchyroll. For some reason it downloaded the season correctly then jumped to episode 3 of the re-edited version(skipped 1 and 2) which is a compilation of multiple episode and still the season one so it was also named "s01e03". So everything's ok in the end, but still, a season filter would be useful is there is none!

**Comment by Godzil** [comment]
Oh! That's a' interesting one. Yeah Crunchy, at the moment, rely only on the scrapped metadata from CR so if they serve two "season 1" the filter will be doing weird things.

I don't remember which serie it was but seasone 2 was incorrectly tagged as season 1 which was also creating issues..

I found a way to get, I think, more consistent data, but need lots of changes in Crunchy code so it will take some times before it hit a release..
