### ISSUE TITLE
Merged season issue

### ISSUE THREAD

**Issue by clienthax** [Godzil/Crunchy#50]
Seems attempting to download this http://www.crunchyroll.com/the-ancient-magus-bride
Will cause both 'seasons' to be downloaded as S1 with -1 -2 -3 appended on the end of the filenames.

**Comment by Godzil** [comment]
See #51, this is mainly CR fault to not properly tag seasons (and in this case to have put OAV and the anime in the same part)

**Comment by Godzil** [comment]
Duplicate of #51
