### ISSUE TITLE
missing subtitles

### ISSUE THREAD

**Issue by izenn** [Godzil/Crunchy#53]
After downloading an episode there are no subtitles being displayed

Steps to reproduce:
downloading using the following command:
`crunchy http://www.crunchyroll.com/is-it-wrong-to-try-to-pick-up-girls-in-a-dungeon`
open in VLC
subtitle track 1 automatically selected (i have also tried disabling and manually selecting track 1)

**Comment by Godzil** [comment]
I *think* it is a VLC bug, I found the same issue recently with VLC where Plex have no problem with them.

Can you try another player to check?

**Comment by izenn** [comment]
You are correct.  MplayerX worked with the subtitles.  Thanks!!!
