### ISSUE TITLE
Can I download Image also?

### ISSUE THREAD

**Issue by skthanu** [Godzil/Crunchy#55]
Hello,
This program is great, however, can you please make a function so that I can download Image from manga also?
Please help/

**Comment by Godzil** [comment]
Do you mean for downloading mangas?

I don't have plan for that right now, but you can use CrunchyManga: https://github.com/7ouma/CrunchyManga which from my test works reasonably well

**Comment by skthanu** [comment]
Thank you so much, I found it some day before and it works great too.
