### ISSUE TITLE
how to use -e filter?

### ISSUE THREAD

**Issue by Nikitarex** [Godzil/Crunchy#61]
i tried some ways but it's very unclear on how to use the episode filter... can you explain better?

**Comment by Jfigs101** [comment]
Use -e to download from a specific episode onwards. For example, -e 3 will
start download episode 4 and above. It will not download a single episode.

**Comment by Nikitarex** [comment]
i tried in this mode:
crunchy -e 14 --output \\NAS-CASA\video http://www.crunchyroll.com/food-wars-shokugeki-no-soma -u username -p password
i get error type 1

**Comment by Godzil** [comment]
I will try to look at it, but I do remember that this flag has always been broken in one way or another way before I made my fork

**Comment by Godzil** [comment]
Filter has been remove part of release 1.3.4, use the @ syntax to download a single episode.

A way of selecting an episode or multiple one from the command line may return later but the form it was was too buggy.
