### ISSUE TITLE
npm test running a bad command

### ISSUE THREAD

**Issue by elisha464** [Godzil/Crunchy#63]
https://github.com/Godzil/Crunchy/blob/b24840543743be9b9ede5f7e1928ef55a7c47d5a/package.json#L45

the linter is not really checking the code
when I loaded the code in my IDE I saw a lot of complaints from the linter
but when I run `npm test` its not telling anything

the command should be `tslint --project .`

**Comment by Godzil** [comment]
Well now it is fixed! Thanks!
