### ISSUE TITLE
Subtitles Not Merging With MP4

### ISSUE THREAD

**Issue by Tompps** [Godzil/Crunchy#71]
**Describe the bug**
The 2 files download fine and merge to the MKV file however when you open the mkv file to watch through the subtitles dont show

**Expected behavior**
For the subtitles to show

**Please fill theses informations:**
(Add a X between brackets to make them ticked)
 - OS: Win 10
 - [X] I'm using the latest version of Crunchy
 - [X] I have a premium accrount on CR
 - Serie you get a problem with (and specify which episode if it is specific to one): Every Series Ive Tried
 - The command line you are running Crunchy with: crunchy -o D:\Anime -u -p -f srt -r 1080 <link>
 - The message Crunchy is giving you, if any: 
```
 * INFO : Crunchy version 1.3.3
 * WARN : Do not use this app without a premium account.
 * INFO : Checking availability for KONOSUBA -God's blessing on this wonderful world!
 > KONOSUBA -God_s blessing on this wonderful world! - s01e01 - [CrunchyRoll] : Finished! (00:06:05)
```

**Comment by Godzil** [comment]
- Why are you forcing the subtitle format to SRT?
- What mkvinfo return about the generated MKV file?
- What player are you using?

**Comment by Godzil** [comment]
PS the log clearly show that downloading the episode worked fine. If you can't see the subtitles from the MKV file, change your video player.
