### ISSUE TITLE
Cant Find Episodes Despite Them Showing On The Site (VPN)

### ISSUE THREAD

**Issue by Tompps** [Godzil/Crunchy#76]
**Describe the bug**
Its saying it cant find the eps even though they are on the site and i can play them there, also using a different downloader works fine, im connected to a Japan VPN on Nord VPN, tried restarting my PC connecting to the VPN then running etc also.

**Expected behavior**
Download the episodes from the Japanese VPN

**Screenshots**
http://prntscr.com/k7ie0a
http://prntscr.com/k7ie7r

**Please fill theses informations:**
(Add a X between brackets to make them ticked)
 - OS: Win 10
 - [X] I'm using the latest version of Crunchy
 - [X] I have a premium accrount on CR
 - Series you get a problem with (and specify which episode if it is specific to one): Anything while connecting to Japanese VPN
 - The command line you are running Crunchy with: crunchy -u -p -m -f srt -o -r 720 http://www.crunchyroll.com/fullmetal-alchemist-brotherhood
 - The message Crunchy is giving you, if any:
```
 * INFO : Crunchy version 1.3.4
 * WARN : Do not use this app without a premium account.
 * INFO : Checking availability for Fullmetal Alchemist: Brotherhood
 * WARN : No episodes found for Fullmetal Alchemist: Brotherhood. Could it be a movie?
Done!
```

**Additional context**
Once I have the VPN off and download a non-region locked show like Angel of Death it works fine, also tried to add .rss at the end of the link.

**Comment by Tompps** [comment]
Updated @Godzil

**Comment by Tompps** [comment]
Trying it with .rss at the end now gives this

`p://www.crunchyroll.com/fullmetal-alchemist-brotherhood.rss
 * INFO : Crunchy version 1.3.4
 * WARN : Do not use this app without a premium account.
 * WARN : Retrying to fetch episodes list from5 / 5
 * WARN : Retrying to fetch episodes list from4 / 5
 * WARN : Retrying to fetch episodes list from3 / 5
 * WARN : Retrying to fetch episodes list from2 / 5`

**Comment by Godzil** [comment]
RSS are not a valid URL for Crunchy.

Could you please run as for the first comment and add the --debug switch to the command line.
It will create a debug.txt file and send it to 

crunchy-debug at godzil dot net

Thanks

You can attach here too, but I can't guaranty that it may not contain some personal information (login/password should not appear but as there are dump of CR pages; I can't guaranty on what they will contain.)

**Comment by Nightmarch1** [comment]
I have the same problem, except that I am not using a VPN. I am using:

`crunchy -u user -p pass -o path link `
 
My problem is that crunchy doesn't work for any series. It returns
```
 INFO : Crunchy version 1.4.2
  * INFO : Seems we are not currently logged. Let's login!
  * WARN : Retrying to fetch episodes list from5 / 5
  * INFO : Seems we are not currently logged. Let's login!
  * INFO : You have a premium account! Good!
  * INFO : Checking availability for BORUTO: NARUTO NEXT GENERATIONS
  * WARN : This serie probably have georestriction and will miss some episodes [Message: Due to the 
 broadcast timeslot change in Japan, Boruto will now launch on Thursdays at 4am PDT.].
  * WARN : No episodes found for BORUTO: NARUTO NEXT GENERATIONS. Could it be a movie?
 Done!`
```
I tried it with different networks but it didn't work, it always says that it can't find the episodes.

**Comment by Godzil** [comment]
Interesting because it properly load the page because of the infobox.

Could you run it with `--debug` and attach the debug file to the ticket, so I can have a look at how the page is looking for crunchy.

**Comment by Nightmarch1** [comment]
Here it is
[debug.txt](https://github.com/Godzil/Crunchy/files/2274049/debug.txt)

**Comment by Godzil** [comment]
Ok ! Great (in a way)

You are using CR in german aren't you?

Crunchy is unable to parse pages in other languages than English (cf #1 )

But with your sample I have now some part for parsing german pages :)

**Comment by Nightmarch1** [comment]
Weird thing is: it worked for me in the past ~4 weeks.

**Comment by Godzil** [comment]
Well there is something I can't control in crunchy (their mechanism is too complex)  is in which languages the pages are served. Going to put a new release that should solve that issue.

**Comment by Godzil** [comment]
@Nightmarch1 Could you please test with the latest update?

**Comment by Nightmarch1** [comment]
Yeah, it works. Thanks :D
