### ISSUE TITLE
-n tag not working as of 1.3.5

### ISSUE THREAD

**Issue by xXxBobDolexXx** [Godzil/Crunchy#78]
This is the command I am running:
crunchy -f srt -u username -p password -n "{SERIES_TITLE} Episode {EPISODE_NUMBER} - {EPISODE_TITLE}" http://www.crunchyroll.com/no-game-no-life 

It worked properly in 1.3.4, but after updating to 1.3.5 it does not apply the formatting anymore, this is the output:
No Game No Life - s01e01 - [CrunchyRoll]

**Comment by Godzil** [comment]
Oh crap! that switch use a stupid name.

Are there anyone using it will the full name "--filename" ?
I want to change it to "--nametmpl" as for name template

**Comment by xXxBobDolexXx** [comment]
--filename has the same results as -n, just tested it

**Comment by Godzil** [comment]
yeah they are equivalent:

`    .option('-n, --filename <s>', 'The name override.')`

**Comment by Godzil** [comment]
Ok do have a fix for it, sorry, cleaning up the code ended with that (the code is really messy), testing it a bit, then will push an update.

**Comment by xXxBobDolexXx** [comment]
Sounds good thank you for looking into it

**Comment by Godzil** [comment]
Should now be fixed in 1.3.6, please if you can test and close if everything works well.

Thanks

**Comment by xXxBobDolexXx** [comment]
Seems to be working, thanks
