### ISSUE TITLE
Error when called without options

### ISSUE THREAD

**Issue by stordoff** [Godzil/Crunchy#88]
**Describe the bug**
Minor thing, but 1.4.3 errors if called without any command line options. 1.3.3 cleanly returns. Compare:

```
C:\Users\stord>crunchy
* INFO : Crunchy version 1.3.3
Done!
```
```
C:\Users\stord>crunchy
 * INFO : Crunchy version 1.4.3
C:\Users\stord\AppData\Roaming\npm\node_modules\crunchy\dist\batch.js:70
        if (tasksArr[0].address === '') {
                        ^

TypeError: Cannot read property 'address' of undefined
    at C:\Users\stord\AppData\Roaming\npm\node_modules\crunchy\dist\batch.js:70:25
    at C:\Users\stord\AppData\Roaming\npm\node_modules\crunchy\dist\batch.js:213:20
    at suppressedCallback (fs.js:240:5)
    at FSReqWrap.oncomplete (fs.js:171:20)
```

**Expected behavior**
Done! and/or show help

**Please fill theses informations:**
 - OS: Win 10
 - [X] I'm using the latest version of Crunchy
 - [X] I have a premium accrount on CR
 - [ ] I am using a VPN
 - My region in the world (country or continent): UK
 - Series you get a problem with (and specify which episode if it is specific to one): N/A
 - The command line you are running Crunchy with: crunchy
 - The message Crunchy is giving you, if any: above

**Comment by Godzil** [comment]
Thank for the report!
 I think I already saw it already but forgot about it.

This only happen if you don’t give an URL on the command line or use a batchfile when you are calling Crunchy.

Will fix that for the next release!
Thanks again!
