### ISSUE TITLE
Skipping/Error 

### ISSUE THREAD

**Issue by yousef-kas133** [Godzil/Crunchy#90]
**Describe the bug**

Some of the episodes is not downloading at all like http://www.crunchyroll.com/a-centaurs-life and http://www.crunchyroll.com/100-teacher-pascal , 100% Teacher Pascal did download only 3 episodes.

 * WARN : Retrying to fetch episode "s1e12" - Retry 1 / 5
 > A Centaur_s Life - s01e12 - We Tried Making a Fantasy Story in RPG Style_ | F
ierce Fights! Arm Wrestling! How Will the Battle of the Heroines End_ - [Crunchy
 > A Centaur_s Life - s01e12 - We Tried Making a Fantasy Story in RPG Style_ | F
ierce Fights! Arm Wrestling! How Will the Battle of the Heroines End_ - [Crunchy
Roll] : Error...
 * ERROR: {"errno":-4058,"code":"ENOENT","syscall":"open","path":"C:\\Users\\Adm
inistrator\\Desktop\\crunchy\\A Centaur_s Life\\A Centaur_s Life - s01e12 - We T
ried Making a Fantasy Story in RPG Style_ | Fierce Fights! Arm Wrestling! How Wi
ll the Battle of the Heroines End_ - [CrunchyRoll].ass"}
 * ERROR: Cannot fetch episode "s1e12", please rerun later
Done!

**Please fill theses informations:**
(Add a X between brackets to make them ticked if relevant)
 - OS: [e.g:. Windows 10, Mac OS X 10.13, ...]
 - [x] I'm using the latest version of Crunchy
 - [x] I have a premium accrount on CR
 - [ ] I am using a VPN
 - My region in the world (country or continent):
 - Serie you get a problem with (and specify which episode if it is specific to one):
 - The command line you are running Crunchy with:
 - The message Crunchy is giving you, if any:

**Comment by Godzil** [comment]
Yeah :/

That’s an old overlook on the windows side, as it does not allow the ‘|’ character in file names.

This has been fixed by #86, and will be part of the next release.

Really sorry about that

**Comment by yousef-kas133** [comment]
Not a problem man, thanks a lot for the hard work i really appreciate it.

**Comment by Godzil** [comment]
Fixed in release 1.4.4
