### ISSUE TITLE
[BUG]  Somethig unexpected in the page, Downloads overwrite each other

### ISSUE THREAD

**Issue by UiharuKazari2008** [Godzil/Crunchy#95]
**Describe the bug**
When requesting a download like "Jormungand" it trows a warning about something unexpended and sets the episode as 0. All downloads are set as 0 so it overwrites all downloads and the only files left is the last episode.
Most series if not all I download cause this issue.

**Expected behavior**
Downloads the episodes correctly with the correct episode number

**Please fill theses informations:**
(Add a X between brackets to make them ticked if relevant)
 - OS: macOS 10.13.6
 - [Y] I'm using the latest version of Crunchy
 - [Y] I have a premium accrount on CR
 - [N] I am using a VPN
 - My region in the world (country or continent): USA
 - Serie you get a problem with (and specify which episode if it is specific to one): https://www.crunchyroll.com/jormungand
 - The command line you are running Crunchy with: crunchy -u y*******@icloud.com -p ************ --ignoredub -r 1080 -m -o /Volumes/Yumehara/Anime/ https://www.crunchyroll.com/jormungand
 - The message Crunchy is giving you, if any: 
```
* INFO : Crunchy version 1.4.4
 * INFO : You have a premium account! Good!
 * INFO : Checking availability for Jormungand
 * INFO : Cannot check version.
 * WARN : Somethig unexpected in the page at https://www.crunchyroll.com/jormungand/episode-1-gunmetal-calico-road-756293 (data are: )
 * WARN : Setting Season to ’0’ and episode to ’0’...
^C  - s00e00 -  - [CrunchyRoll] : Fetching video...
```

**Additional context**
Would be nice it if would use the data returned in the URL to get the episode number as a fallback or just index them as they download. 

_Also don't hesitate to add labels you feel apropriate on your report._
_Please don't edit logs if you are adding them, apart from removing sensitive informations like login/password_

**Comment by Godzil** [comment]
Thanks for the report.

Something is off there, first time I see that. Not sure if I will be able to do something for it.
It may not be fixed for the next release.

**Comment by invisan** [comment]
Works fine for me under Windows with 1.4.4

Try the following line:

crunchy --output /Volumes/Yumehara/Anime/ -p pass -u user http://www.crunchyroll.com/jormungand -n "{SERIES_TITLE} S{SEASON_NUMBER} Ep{EPISODE_NUMBER} - {EPISODE_TITLE}" --ignoredub -r 1080 -m

**Comment by UiharuKazari2008** [comment]
Ya that works and I can download stuff now
