### ISSUE TITLE
[Feature] Force Login

### ISSUE THREAD

**Issue by invisan** [Godzil/Crunchy#96]
**Is your feature request related to a problem? Please describe.**
It happens more then enough when i try to download an Episode that Crunchy says im not logged in trying to log. And goes from 5 to 0 Attempts without anything happening.

**Describe the solution you'd like**
Would it be possible to Add a function to add to the cmdline which login method you would like to try and to only login without downloading?

**Describe alternatives you've considered**
Downloading like normal and trying again and again till it finally logs me in.

**Additional context**
Nothing to add.

**Comment by Godzil** [comment]
During each retry it try to login, there is a known issue with Crunchy where the login fail for some (unknown) reason.

There is a limit on the number of retry to avoid an infinite loop, but you can set that number on the command line using the `--retry` parameter. By default it is 5, but you can set to a higher value.
